### ISSUE TITLE
Создание соревновательной проверялки

### ISSUE THREAD

**Issue by Easterdie** [lex128/mtasa-tactics#48]
http://puu.sh/oaFoc/368f8d4e3c.png

список с серийным номером и ником

если игрока нет в списке, то по нижнему выпадающему списку применять действие на игрока

галочка ник - заменять ник
после выхода всех с сервера атвоматом чистить список

читать строки в гуи, форматы:
серийник ник
серийник разделитель ник
вырезать разделитель, ограниченный пробелами

**Comment by lex128** [comment]
Дублирует #6
