### ISSUE TITLE
race / dd 

### ISSUE THREAD

**Issue by Easterdie** [lex128/mtasa-tactics#50]
для этих режимов сделать обратное время, которое стартует от нуля и идёт вверх.

**Comment by lex128** [comment]
> Lex128: А на дд есть время раунда?
> Lex128: И в какую сторону оно идёт (если есть), в уменьшение или в увеличение?
> DD FATHER: Есть, в уменьшение
> Lex128: А на рейсе?
> DD FATHER: аналогично

Сейчас всё верно, время раунда идёт в уменьшение до нуля, а вот личное время игрока пишется в его табличке и там да, идёт на увеличение
