### ISSUE TITLE
Автоматическое создание команд по тегу в нике

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lex128/mtasa-tactics#6]
```
Полная суть предложения:
Создание команд по тегам кланов, задать 5-10 
названий команд для режима дерби и рейс, 
чтобы команды могли без изменения конфига 
менять себе цвет в режимах ДД и Рейс на 
пабликах. Например названия от T1 до T10 
разных цветов, Bpb синего цвета, U1tra зёлёного 
и так далее.

Дополнительные сведения:
Образец рабочего внешнего скрипта можно 
взять у меня в аське.
```

Original issue reported on code.google.com by `easter...@gmail.com` on 9 Sep 2012 at 8:58

**Comment by lex128** [comment]
Появилась идея, совместить вайтлист для турниров и автосоздание команд
Например сделать во вкладке **Команды** флажок
- [ ] Динамические команды

при включении которого, все команды(кроме судейской) в которых нет игроков скрываются из таба, и появляется функционал задавать для каждой команды список игроков, просто вписывая их в текстовое поле, раскрывающееся под командой, в формате 1 строка = 1 игрок:
> СЕРИЙНЫЙНОМЕРСЕРИЙНЫЙНОМЕРСЕРИЙ Никнейм
> СЕРИЙНЫЙНОМЕРСЕРИЙНЫЙНОМЕРСЕРИЙ Никнейм

И при заходе на сервер игроку не даётся возможности выбирать команду, вместо этого все распределяются согласно этим спискам

**Comment by lex128** [comment]
Добавлено меню **Состав** во вкладке **Команды**, которое устанавливает состав игроков для команды. Если состав определён, то такая команда скрывается, когда в ней нет игроков. Кроме того, на экране входа к выбору добавляются команды, в составе которых состоит игрок
